export const TEAM_NAME_MAP: Record<string, string> = {
  'argentina': 'ARG', 'brazil': 'BRA', 'france': 'FRA', 'germany': 'GER',
  'spain': 'ESP', 'england': 'ENG', 'italy': 'ITA', 'netherlands': 'NED',
  'portugal': 'POR', 'belgium': 'BEL', 'croatia': 'CRO', 'uruguay': 'URU',
  'mexico': 'MEX', 'usa': 'USA', 'canada': 'CAN', 'japan': 'JPN',
  'south-korea': 'KOR', 'morocco': 'MAR', 'senegal': 'SEN', 'australia': 'AUS',
  'qatar': 'QAT', 'colombia': 'COL', 'ecuador': 'ECU', 'paraguay': 'PAR',
  'cameroon': 'CMR', 'ghana': 'GHA', 'panama': 'PAN', 'iran': 'IRN',
  'saudi-arabia': 'KSA', 'finland': 'FIN', 'wales': 'WAL', 'nigeria': 'NGA',
  'serbia': 'SRB', 'jamaica': 'JAM', 'algeria': 'ALG', 'chile': 'CHI',
  'poland': 'POL', 'sweden': 'SWE', 'switzerland': 'SUI', 'denmark': 'DEN',
  'norway': 'NOR', 'ukraine': 'UKR', 'greece': 'GRE', 'turkey': 'TUR',
  'romania': 'ROM', 'austria': 'AUT', 'czech-republic': 'CZE', 'hungary': 'HUN',
  'scotland': 'SCO', 'peru': 'PER', 'venezuela': 'VEN', 'tunisia': 'TUN',
  'new-zealand': 'NZL', 'united-states': 'USA',
  'swiss': 'SUI', 'czech': 'CZE', 'southkorea': 'KOR', 'saudiarabia': 'KSA',
  'united states': 'USA', 'south korea': 'KOR', 'saudi arabia': 'KSA',
  'czech republic': 'CZE', 'new zealand': 'NZL',
  'united-states-of-america': 'USA',
}
